language: node_js

node_js:
  - 0.12

branches:
  only:
    - master

env:
  global:
    - secure: "forZZ0jHMGDmjaiOthXwq90UYZo2mSxvH3ixg/k3wpzZffFZ+YLRCvZEHczs/IlWUiwFi6CAJTu9CEIWl+IMVUdv7T+USzLEdYaGz9swfMkvXcaju897OmQsw7E4WH5jvEtYvlhferbCk5iIo75gDdQAeUsnQw6MAltZX8F7WJqNt9e6vvJDRa0vlLCILYax+7Z0FiZhlVv+qWg6F/+C5JB1IvVZRXtr8txdmC+AwvdlbqzuEai7O1P65NVmA0n9VYFTYLFA59m+kJ8zCgC52YSFfpVrQUu38R9BrKXayGU9sw0L0Lm3YIivSCCnJ7W3s2x+KIimION4gUwzOOmM0XorhYgvim6lpgXHTRevzrh9Q/7P5uN+4jQfgpW9sEbIQS6h1sEHRgiP5MkaSUbZBp0hDVV/L7xTYt6pzRXBGTmZIKMr2wO0fCPPTEQgNO9h4lBHPQM+ftbfGqmVamjUiKkQOu1L0MHak1WOkM2xb2nKvT+9uHJK5EVZLPF1/JlLLyWWmxQ2bnsxXDiyO0KhOQkytJ74MYbZ29jJuCSP1+ZxYp3GK7EVsaQy++uOdYEw/9VMnnJX0TZMqLYBHl9b1NpkkYwoNMjbx2WZnoIsD1DdcNFalvTX6a1IcYx/9LrqahC2BQglJzuXLUdBZkUzg70PHfb7okymBDvHWbi+oKI="
    - GH_OWNER: zijpn
    - GH_PROJECT_NAME: ml

before_script:
  - npm install -g gulp bower

script:
  - bower install
  - gulp

after_success:
  - git submodule add -b gh-pages https://github.com/${GH_OWNER}/${GH_PROJECT_NAME} site
  - cd site
  - git rm -r .
  - cp -R ../dist/* .
  - cp ../dist/.htaccess .
  - git add .
  - git config user.email ""
  - git config user.name "Nico Verzijp"
  - git commit -am "Deploy build to gh-pages [ci skip]"
  # Any command using GH_OAUTH_TOKEN must pipe the output to /dev/null (to not expose your oauth token)
  - git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:gh-pages > /dev/null 2>&1
